### ISSUE TITLE
Bow pullback animation?

### ISSUE THREAD

**Issue by Redblock6YT** [ViaVersion/ViaRewind-Legacy-Support#31] opened 2021-07-26 23:33 UTC
Hello,
I was wondering if you could implement the bow pullback animation for all versions?

Thanks,
Redblock6

**Comment by creeper123123321** [comment] 2021-07-26 23:44
duplicate of https://github.com/ViaVersion/ViaRewind/issues/64

**Closed by creeper123123321** 2021-07-26 23:44 UTC

**Comment by Redblock6YT** [comment] 2021-07-26 23:48
Thanks.
