### ISSUE TITLE
Server freezes after few minutes (playBlockPlaceSoundNMS NPE)

### ISSUE THREAD

**Issue by BestMark** [ViaVersion/ViaRewind-Legacy-Support#63] opened 2023-06-11 07:32 UTC
**Crash log:** https://pastebin.com/bt2rZ1GB

**Software:**
Latest ViaVersion, ViaBackwards and ViaRewind and ViaRewindLegacySupport (1.4.2) from Hungar
Server version: Paper 1.12.2 (latest build)
ProtocolLib version: 4.8.0

**Comment by HowardZHY** [comment] 2023-06-14 07:10
https://github.com/ViaVersion/ViaRewind-Legacy-Support/issues/58

**Comment by TheJoshue** [comment] 2023-08-10 21:41
I confirm this happens even with latest versions of the date and time i am writing this message.
![image](https://github.com/ViaVersion/ViaRewind-Legacy-Support/assets/56804505/ce3c2dda-dcb2-4f05-99f4-1afb488e1630)

**Comment by SladeHazard** [comment] 2023-09-26 20:04
happening to me as well, please fix this the plugin is completely unusable,

[19:43:01] [Server thread/INFO]: [Essentials] CONSOLE issued server command: /give ElectroPika cake 1
[19:43:01] [Server thread/INFO]: ARCHER » Giving 1 of cake to ElectroPika. 
[19:43:01] [Server thread/INFO]: <Archer> left
[19:43:02] [Server thread/WARN]: java.lang.NullPointerException
[19:43:02] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.playBlockPlaceSoundNMS(SoundListener.java:146)
[19:43:02] [Server thread/WARN]: 	at de.gerrygames.viarewind.legacysupport.listener.SoundListener.onBlockPlace(SoundListener.java:73)
[19:43:02] [Server thread/WARN]: 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1568.execute(Unknown Source)
[19:43:02] [Server thread/WARN]: 	at org.bukkit.plugin.EventExecutor$2.execute(:70)
[19:43:02] [Server thread/WARN]: 	at co.aikar.timings.TimedEventExecutor.execute(:74)
[19:43:02] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(:62)
[19:43:02] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(:513)
[19:43:02] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callBlockPlaceEvent(:152)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ItemStack.placeItem(:237)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerInteractManager.a(:551)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(:1021)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(:37)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PacketPlayInUseItem.a(:5)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(:14)
[19:43:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[19:43:02] [Server thread/WARN]: 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.SystemUtils.a(:46)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(:854)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(:432)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778)
[19:43:02] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669)
[19:43:02] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:829)
[19:43:02] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(:958) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(:432) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-cdba3ce]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.server.v1_12_R1.ItemStack.usesData(:366) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.setData(:394) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.<init>(:90) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(:506) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(:25) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(:974) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.Container.b(:84) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(:291) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(:1857) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.h(:1827) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.WorldServer.l(:728) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.tickEntities(:1600) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(:705) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(:947) ~[server.jar:git-Paper-cdba3ce]
	... 4 more
[19:43:02] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NullPointerException: null
	at net.minecraft.server.v1_12_R1.ItemStack.usesData(:366) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.setData(:394) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.<init>(:90) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.ItemStack.cloneItemStack(:506) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.PacketPlayOutSetSlot.<init>(:25) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.EntityPlayer.a(:974) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.Container.b(:84) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.EntityPlayer.B_(:291) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(:1857) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.h(:1827) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.WorldServer.l(:728) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.World.tickEntities(:1600) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(:705) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(:947) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(:432) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(:778) ~[server.jar:git-Paper-cdba3ce]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(:669) ~[server.jar:git-Paper-cdba3ce]
	at java.lang.Thread.run(Thread.java:829) [?:?]
[19:43:02] [Server thread/ERROR]: This crash report has been saved to: /home/container/./crash-reports/crash-2023-09-26_19.43.02-server.txt
[19:43:02] [Server thread/INFO]: Stopping server

**Comment by FlorianMichael** [comment] 2024-04-02 10:17
Fixed in latest master commit

**Closed by FlorianMichael** 2024-04-02 10:17 UTC
