### ISSUE TITLE
Constant spam when the latest version of ViaVersion is downloaded

### ISSUE THREAD

**Issue by GLMidnight** [ViaVersion/ViaRewind-Legacy-Support#74] opened 2024-02-21 00:02 UTC
```
20.02 23:57:40 [Server] [WARN] [ViaRewind-Legacy-Support] Task #32 for ViaRewind-Legacy-Support v1.5.0-SNAPSHOT generated an exception
20.02 23:57:40 [Server] [INFO] java.lang.NoSuchMethodError: 'com.viaversion.viaversion.api.protocol.version.ProtocolVersion com.viaversion.viaversion.api.protocol.version.ServerProtocolVersion.lowestSupportedProtocolVersion()'
20.02 23:57:40 [Server] [INFO] at com.viaversion.viarewind.legacysupport.BukkitPlugin$1.run(BukkitPlugin.java:52) ~[ViaRewind%20Legacy%20Support.jar:?]
20.02 23:57:40 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1636) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1515) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"4939f87"]
20.02 23:57:40 [Server] [INFO] at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Just constantly spams console making it unusable.

**Comment by Kichura** [comment] 2024-02-21 04:33
Duplicate of #73 - current build of this plugin only works with dev builds of via*.

**Closed by Kichura** 2024-02-21 04:33 UTC
