### ISSUE TITLE
Viarewind warning when placing block

### ISSUE THREAD

**Issue by SaltyPotata** [ViaVersion/ViaRewind-Legacy-Support#52] opened 2022-09-02 09:15 UTC
**Describe the bug, provide any errors**
When placing a block a warning appears https://hastebin.com/ubiresariz.md

**How can we reproduce it?**
1. Tested on 1.8
2. Place a block
3. It gives you this warning: https://hastebin.com/ubiresariz.md

**ViaVersion Dump:**
- https://dump.viaversion.com/78ad18ab1dabd692538b9218f898a28010e9191860ef587f6391727cb7e880a2

**Additional server info**
Using paperspit 1.19.2

**Checklist** (mark with [X] to check)
- [] I have included a ViaVersion dump X
- [] If applicable, I have included a paste (not a screenshot) of the error X
- [] I have tried a build from https://ci.viaversion.com/ and the issue still persists X
- [] I have looked at https://www.spigotmc.org/resources/viarewind-legacy-support.52924/ and it does not offer a fix for my problem X

**Comment by PierreSchwang** [comment] 2022-09-02 22:26
Duplicate of https://github.com/ViaVersion/ViaRewind-Legacy-Support/issues/45 - would be closed by https://github.com/ViaVersion/ViaRewind-Legacy-Support/pull/48

**Closed** 2022-09-02 22:52 UTC
